DROP TABLE IF EXISTS routes;

CREATE TABLE routes (
  id SERIAL PRIMARY KEY,
  driver_id VARCHAR(256) NOT NULL,
  name VARCHAR(256) NOT NULL,
  date date NOT NULL REFERENCES users(id) ON DELETE CASCADE
);
